language: generic
os:
- linux
script:
- make
after_success:
- mv current.zip $TRAVIS_TAG.zip

deploy:
  provider: releases
  api_key:
    secure: SmZnvIJtmXI92VR/8X8GG9WT0GiQSWpptypioCN37Y5Yr55ncl3Jc48j94FTfgf0Eolbu54SctrWAwk6mASyl5CzY3vcSHcxTutOnbMCMjZ+Ahm/XVXZCcBwLJhOVX7meVsvSSowyEi4usIhujpZPe5mNYuRr7urSb+cFVJl70MbSKQ0QWgsXzzdGHTe39P0Q4H2Svwe77Bzhf5pF3ahgtZ6GbC8Xy7t8xnGheMYEst5GWMPW7a4Jzp08FTJBrvK/rK7nxrmpG2LXYAjQCEvy05cF7lUFr4Ho5Ep9/QR/n518QmS+1wwRm4sIb6qWaLiA3pw5iuR7N/JnTqW6dxHsriAnJnPOXfnQTR3d++yUy3kbOXff6fYs135rWphPE2HbXtbrh4gLybS/C7OQJNcLhoFUz32c8GVHX6pVKgOqDUwO+yd1PqmHZs6kq7Mhp/uj0lfcuOUa20YGovsPo+cU6H2jIkVJG3oiraoR8SOfVvzxaYboGNu0Ai470IfPPp2OCqC0t3n8h7P2bL2QNSpS+2d1DlOynTn3HDE+EX5hwjzAfC9Q6BRmBNL6GX07H/RAPkbQJu3P99FySUywK6t581RhUMhLCuN9Dnlbp/tUVISzzroV7liaRuu2r/wzDRvk41O7r8Pt5Z2Ow/b08fCL+dz5LridD9dzSO8UR/FWHY=
  file_glob: true
  file: ./*.zip
  skip_cleanup: true
  on:
    repo: olav-st/screencloud-dropbox
    tags: true
